import { readFileSync } from 'node:fs'
import { test, expect } from '@playwright/test'

const source = readFileSync('public/content/xwh-manual-2026.md', 'utf8')

test('首页和来源页准确区分手册全文导入与原有教学摘录', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('link', { name: '采集手册', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '来源', exact: true }).click()
  const manualSource = page.locator('.source-library-card').filter({ hasText: '标本采集手册' })
  await expect(manualSource).toContainText('全文已接入')
  await expect(manualSource).toContainText('517')
  await expect(manualSource).toContainText('233')
  await expect(manualSource).not.toContainText('仅抽取少量说明')
  await manualSource.getByRole('link', { name: '阅读完整手册', exact: true }).click()
  await expect(page).toHaveURL(/#\/manual/)
})

test('按检验分组筛选并分页，项目详情完整显示原字段与同上依据', async ({ page }) => {
  await page.goto('/#/items')
  await expect(page.getByRole('heading', { name: '检验项目速查', exact: true })).toBeVisible()
  await expect(page.locator('.item-row')).toHaveCount(40)
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  await expect(page).toHaveURL(/page=2/)
  await page.getByRole('link', { name: '分子生物', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('49')
  await page.getByRole('searchbox', { name: '搜索检验项目' }).fill('FLUA-RNA')
  await page.getByRole('link', { name: '甲型流感病毒RNA', exact: true }).click()
  await page.getByText('完整原表字段与表后说明', { exact: true }).click()
  await expect(page.locator('.manual-fields > div')).toHaveCount(8)
  const timing = page
    .locator('.manual-fields > div')
    .filter({ has: page.getByText('常规报告时间', { exact: true }) })
  await expect(timing).toContainText('同上')
  await expect(timing).toContainText('3 个工作日')
  await expect(page.getByRole('heading', { name: '本组表后说明', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '本院信息待补充', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: '查看原表与上下文', exact: true }).click()
  await expect(page).toHaveURL(/section=table-4-7&line=2745/)
  await expect(page.locator('#manual-line-2745')).toBeFocused()
  await expect(page.locator('#manual-line-2745')).toContainText('FLUA-RNA')
})

test('完整手册可导航、全文检索、下载原文，保留空白行及表后说明', async ({ page }) => {
  await page.goto('/#/manual')
  await expect(page.getByRole('heading', { name: '2026标本采集手册', exact: true })).toBeVisible()
  const chapters = page.getByRole('combobox', { name: '手册章节' })
  await expect(chapters.locator('option')).toHaveCount(233)
  await expect(page.locator('.manual-reading')).toContainText('2028.04.30')
  const download = page.getByRole('link', { name: '下载完整原文（Markdown）' })
  const response = await page.request.get((await download.getAttribute('href'))!)
  expect(await response.text()).toBe(source)
  await chapters.selectOption('table-4-7')
  await expect(page.locator('.manual-reading tbody tr')).toHaveCount(50)
  await expect(page.locator('#manual-line-2738')).toContainText('原文空白')
  await expect(page.locator('.manual-reading')).toContainText('“-”表示对本项目不适用。')
  await page.getByRole('searchbox', { name: '搜索手册全文' }).fill('血细胞附壁')
  await expect(page.getByRole('link', { name: '3．血细胞附壁', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '3．血细胞附壁', exact: true }).click()
  await expect(page.locator('.manual-reading h2')).toHaveText('3．血细胞附壁')
  await page.reload()
  await expect(page.locator('.manual-reading h2')).toHaveText('3．血细胞附壁')
})
